### ISSUE TITLE
Does gripmock allow to change stubs while the server is running?

### ISSUE THREAD

**Issue by sonic555gr** [bavix/gripmock#400]
Hello! 

I'm a Mobile Engineer and we are implementing UI automation for our app and our services are gRPC based. This tool seems perfect for the job of stubbing gRPC responses for our tests and I would like to understand more before I introduce it to my team. 

Performing automation requires sometimes to alter responses during execution for the same API requests 
ex. 
1. Create user, Receive "Success"
2. Try to create user again, Receive "User already exists" 

Does gripmock allow for the change of stubs while the server is running? 
Can I pass a string or a serialised json dynamically while the server is running? 
If not, how long would it take to implement said feature? 

Thank you.

**Comment by rez1dent3** [comment]
Hello, @sonic555gr 

> Performing automation requires sometimes to alter responses during execution for the same API requests
ex.
> Create user, Receive "Success"
> Try to create user again, Receive "User already exists"

Unfortunately, there is no way to describe such dynamics. You will have to update the stab via REST API before the second request in the tests.

> Does gripmock allow for the change of stubs while the server is running?

Yes, you can update stub using rest api.

> Can I pass a string or a serialised json dynamically while the server is running?

The architecture is as follows.
Two servers are launched:
1. Rest API, which works with stubs;
2. gRPC server generated from proto-files;

Via rest api you can dynamically change stubs.


Rest API: https://bavix.github.io/gripmock-openapi/

**Comment by sonic555gr** [comment]
Perfect. That answers my questions. Thanks

**Comment by rez1dent3** [comment]
I think this issue can be closed. If you have any more questions, create a new one.
