### ISSUE TITLE
Go module not included for well known type: googleapis/type/date

### ISSUE THREAD

**Issue by Tom-Hudson** [bavix/gripmock#449]
When a proto uses a googleapis/type/date type, the proto is already bundled in the docker image but not the go module, so when trying to start the server, you get this error:

```
2024-12-04T07:38:07Z INF Starting GripMock release=v2.7.0
2024-12-04T07:38:07Z INF stub-manager started addr=0.0.0.0:4771
2024-12-04T07:38:07Z INF gRPC-service started pid=47
protogen/proto/example.pb.go:11:2: no required module provides package google.golang.org/genproto/googleapis/type/date; to add it:
        go get google.golang.org/genproto/googleapis/type/date
2024/12/04 07:38:08 exit status 1
```

I am currently building a mock image bundled with stubs for reuse, so to fix this, I added a `RUN go get google.golang.org/genproto/googleapis/type/date` step to Dockerfile to get the dependency in the container and everything just worked. I feel since the well known type protos are already bundled then the modules to make them work should be too.

Thank for this fork, it's brilliant and solves some real headaches!

**Comment by rez1dent3** [comment]
@Tom-Hudson Hello. Thank you. Tag v2.7.1.
The build has been launched. It will be ready in 15-20 minutes.
Please write here when you check it.

**Comment by rez1dent3** [comment]
Added to version 3.x as well.

**Comment by Tom-Hudson** [comment]
@rez1dent3 I just tried the latest version and it has indeed fixed the issue! Thanks for the super fast response to this 🚀
